version: '3'

services:  
  # Contacts Microservice
  rc-contacts:
      build:
        context: ./rc-contacts
        dockerfile: Dockerfile
      depends_on:
        - rc-db
      ports:
        - "8000:8000"
      volumes:
        - ./rc-contacts:/var/www/html
      env_file:
        - ./rc-contacts/.env

  # MySQL database
  rc-db:
    container_name: rc-db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube
      - MYSQL_DATABASE=roundcube
      - MYSQL_USER=roundcube
      - MYSQL_PASSWORD=roundcube
    ports:
      - "3306:3306"
  