version: '3'

services:  
  # Contacts Microservice
  # rc-contacts:
  #     build:
  #       context: ./rc-contacts
  #       dockerfile: Dockerfile
  #     depends_on:
  #       - rc-db
  #     ports:
  #       - "8000:8000"
  #     volumes:
  #       - ./rc-contacts:/var/www/html
  #     env_file:
  #       - ./rc-contacts/.env

  # Login Microservice
  rc-login:
    build:
      context: ./rc-login
      dockerfile: Dockerfile
    depends_on:
      - rc-db
    ports:
      - "8001:8000"
    volumes:
      - ./rc-login:/var/www/html
    env_file:
      - ./rc-login/.env

  # MySQL database
  rc-db:
    container_name: rc-db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube
      - MYSQL_DATABASE=roundcube
      - MYSQL_USER=roundcube
      - MYSQL_PASSWORD=roundcube
    ports:
      - "3306:3306"

  # Poste.io IMAP server
  posteio:
    image: analogic/poste.io:latest
    container_name: posteio
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - ./dovecot.conf:/etc/dovecot/conf.d/99-custom-config.conf

    environment:
      - "TZ=America/New_York"
  